### ISSUE TITLE
Wrong address for GItHub GraphQL Schema

### ISSUE THREAD

**Issue by Joshua-rose** [Joshua-rose/github-issues-to-excel#1]
Error recieved:
```bash
15:41 Repos $ yarn run codegen
yarn run v1.22.4
$ graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate
/process/task_queues.js:97:5)
    Error: Failed to load schema
        at loadSchema (/home/joshua/Development/github-issues-to-excel/node_modules/@graphql-codegen/cli/bin.js:505:15)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)


Something went wrong
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Joshua-rose** [comment]
correct address is `https://api.github.com/graphql`
